services:
  musicapi:
    image: binaryify/netease_cloud_music_api:latest
    container_name: netease-cloud-music-api
    networks:
      - ts3audiobot-netease

  ts3audiobot:
    depends_on:
      - musicapi
    image: appe233/ts3audiobot:0.12.0
    container_name: ts3audiobot
    volumes:
      - ./bot.toml:/app/bots/default/bot.toml
      - ./YunSettings.yml:/app/plugins/YunSettings.yml
      - ./YunSettings.yml:/app/data/plugins/YunSettings.yml
    networks:
      - ts3audiobot-netease
    environment:
      - COMPlus_gcServer=0 # 如果你的内存较小，则需要设置这一项

networks:
  ts3audiobot-netease:
    name: ts3audiobot-netease