services:
  neteasecloudmusicapi:
    image: binaryify/netease_cloud_music_api:latest

  ts3audiobot:
    depends_on:
      - neteasecloudmusicapi
    image: appe233/ts3audiobot-netease:3.0.2
    volumes:
      - type: bind
        source: ./app/bots/default/bot.toml
        target: /app/bots/default/bot.toml